// SPDX-License-Identifier: Apache-2.0

#include "vksplat/spirv/translator.h"

#include <algorithm>
#include <cctype>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <unordered_map>
#include <utility>
#include <vector>

namespace vksplat::spirv {
namespace {

enum class Target {
    C,
    CUDA,
};

std::string sanitize_identifier(std::string value, std::string fallback) {
    if (value.empty()) value = std::move(fallback);
    for (char& c : value) {
        if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_') c = '_';
    }
    if (value.empty() || std::isdigit(static_cast<unsigned char>(value[0]))) {
        value.insert(value.begin(), '_');
    }
    return value;
}

const EntryPoint& first_entry_point(const Module& module) {
    if (module.entry_points.empty()) {
        throw std::runtime_error("SPIR-V translation requires at least one OpEntryPoint");
    }
    return module.entry_points.front();
}

void emit_header(std::ostringstream& out, const Module& module, const char* target) {
    out << "/* Generated by vkSplat SPIR-V to " << target << " restricted translator. */\n";
    out << "/* SPIR-V version word: 0x" << std::hex << module.version
        << ", bound: " << std::dec << module.bound << " */\n";
    out << "/* Opcode coverage: minimal compute memory/arithmetic subset; semantic lowering is incremental. */\n\n";
}

std::string id_name(std::uint32_t id, const Analysis& analysis, const char* prefix) {
    const auto it = analysis.names.find(id);
    if (it != analysis.names.end() && !it->second.empty()) {
        return sanitize_identifier(it->second, std::string(prefix) + std::to_string(id));
    }
    return std::string(prefix) + std::to_string(id);
}

std::string c_scalar_type(const Type& type) {
    switch (type.kind) {
        case TypeKind::Bool:
            return "uint8_t";
        case TypeKind::Int:
            if (type.width <= 8) return type.signedness ? "int8_t" : "uint8_t";
            if (type.width <= 16) return type.signedness ? "int16_t" : "uint16_t";
            if (type.width <= 32) return type.signedness ? "int32_t" : "uint32_t";
            return type.signedness ? "int64_t" : "uint64_t";
        case TypeKind::Float:
            if (type.width == 32) return "float";
            if (type.width == 64) return "double";
            return "float";
        case TypeKind::AccelerationStructure:
            return "const void";
        case TypeKind::RayQuery:
            return "vksplat_ray_query";
        default:
            return "uint32_t";
    }
}

std::string c_type_for_id(std::uint32_t type_id, const Analysis& analysis) {
    const auto it = analysis.types.find(type_id);
    if (it == analysis.types.end()) return "uint32_t";
    const Type& type = it->second;
    if (type.kind == TypeKind::Pointer) {
        const auto pointee_it = analysis.types.find(type.element_type_id);
        if (pointee_it == analysis.types.end()) return "void*";
        return c_scalar_type(pointee_it->second) + "*";
    }
    return c_scalar_type(type);
}

std::uint32_t runtime_array_element_type(std::uint32_t type_id, const Analysis& analysis) {
    const auto type_it = analysis.types.find(type_id);
    if (type_it == analysis.types.end()) return 0;

    const Type& type = type_it->second;
    if (type.kind == TypeKind::RuntimeArray) return type.element_type_id;
    if (type.kind == TypeKind::Struct && !type.member_type_ids.empty()) {
        const auto member_it = analysis.types.find(type.member_type_ids.front());
        if (member_it != analysis.types.end() && member_it->second.kind == TypeKind::RuntimeArray) {
            return member_it->second.element_type_id;
        }
    }
    return 0;
}

std::string parameter_type(const Variable& variable, const Analysis& analysis) {
    const std::uint32_t runtime_element_type =
        runtime_array_element_type(variable.pointee_type_id, analysis);
    if (runtime_element_type != 0) {
        const auto element_it = analysis.types.find(runtime_element_type);
        if (element_it != analysis.types.end()) {
            return c_scalar_type(element_it->second) + "*";
        }
    }
    return c_type_for_id(variable.result_type_id, analysis);
}

std::string constant_expr(const Constant& constant, const Analysis& analysis) {
    const auto type_it = analysis.types.find(constant.type_id);
    if (type_it != analysis.types.end() && type_it->second.kind == TypeKind::Float) {
        if (type_it->second.width == 32) {
            union {
                std::uint32_t u;
                float f;
            } bits = { static_cast<std::uint32_t>(constant.value) };
            std::ostringstream out;
            out << std::showpoint << bits.f << "f";
            return out.str();
        }
    }
    std::ostringstream out;
    out << constant.value;
    if (type_it != analysis.types.end() && type_it->second.kind == TypeKind::Int &&
        !type_it->second.signedness) {
        out << "u";
    }
    return out.str();
}

std::vector<Variable> interface_variables(const Analysis& analysis) {
    std::vector<Variable> variables;
    for (const auto& [_, variable] : analysis.variables) {
        if (variable.storage_class == StorageClass::CrossWorkgroup ||
            variable.storage_class == StorageClass::Uniform ||
            variable.storage_class == StorageClass::StorageBuffer ||
            variable.storage_class == StorageClass::UniformConstant ||
            variable.storage_class == StorageClass::PushConstant) {
            variables.push_back(variable);
        }
    }
    std::sort(variables.begin(), variables.end(), [](const Variable& a, const Variable& b) {
        if (a.has_descriptor_set != b.has_descriptor_set) return a.has_descriptor_set;
        if (a.has_descriptor_set && a.descriptor_set != b.descriptor_set) {
            return a.descriptor_set < b.descriptor_set;
        }
        if (a.has_binding != b.has_binding) return a.has_binding;
        if (a.has_binding && a.binding != b.binding) return a.binding < b.binding;
        return a.id < b.id;
    });
    return variables;
}

bool has_global_invocation_id(const Analysis& analysis) {
    for (const auto& [_, variable] : analysis.variables) {
        if (variable.has_builtin && variable.builtin == 28) return true; // GlobalInvocationId
    }
    return false;
}

std::string parameter_list(const Analysis& analysis, Target target) {
    const std::vector<Variable> variables = interface_variables(analysis);
    const bool emit_global_id_params = target == Target::C && has_global_invocation_id(analysis);
    if (variables.empty() && !emit_global_id_params) return "void";

    std::ostringstream out;
    bool emitted = false;
    for (std::size_t i = 0; i < variables.size(); ++i) {
        if (emitted) out << ", ";
        out << parameter_type(variables[i], analysis) << " "
            << id_name(variables[i].id, analysis, "ptr_");
        emitted = true;
    }
    if (emit_global_id_params) {
        if (emitted) out << ", ";
        out << "uint32_t global_invocation_id_x, uint32_t global_invocation_id_y, "
               "uint32_t global_invocation_id_z";
    }
    return out.str();
}

std::string json_escape(const std::string& value) {
    std::ostringstream out;
    for (char c : value) {
        switch (c) {
            case '"': out << "\\\""; break;
            case '\\': out << "\\\\"; break;
            case '\b': out << "\\b"; break;
            case '\f': out << "\\f"; break;
            case '\n': out << "\\n"; break;
            case '\r': out << "\\r"; break;
            case '\t': out << "\\t"; break;
            default:
                if (static_cast<unsigned char>(c) < 0x20u) {
                    out << "\\u" << std::hex << std::setw(4) << std::setfill('0')
                        << static_cast<unsigned int>(static_cast<unsigned char>(c))
                        << std::dec << std::setfill(' ');
                } else {
                    out << c;
                }
                break;
        }
    }
    return out.str();
}

std::string value_expr(std::uint32_t id,
                       const Analysis& analysis,
                       const std::unordered_map<std::uint32_t, std::string>& expressions) {
    const auto expr_it = expressions.find(id);
    if (expr_it != expressions.end()) return expr_it->second;
    const auto const_it = analysis.constants.find(id);
    if (const_it != analysis.constants.end()) return constant_expr(const_it->second, analysis);
    return "id_" + std::to_string(id);
}

bool pointer_is_interface_variable(std::uint32_t id, const Analysis& analysis) {
    const auto it = analysis.variables.find(id);
    return it != analysis.variables.end() &&
           (it->second.storage_class == StorageClass::CrossWorkgroup ||
            it->second.storage_class == StorageClass::StorageBuffer ||
            it->second.storage_class == StorageClass::UniformConstant);
}

bool is_acceleration_structure_variable(std::uint32_t id, const Analysis& analysis) {
    const auto variable_it = analysis.variables.find(id);
    if (variable_it == analysis.variables.end()) return false;
    const auto type_it = analysis.types.find(variable_it->second.pointee_type_id);
    return type_it != analysis.types.end() &&
           type_it->second.kind == TypeKind::AccelerationStructure;
}

bool is_ray_query_variable(std::uint32_t id, const Analysis& analysis) {
    const auto variable_it = analysis.variables.find(id);
    if (variable_it == analysis.variables.end()) return false;
    const auto type_it = analysis.types.find(variable_it->second.pointee_type_id);
    return type_it != analysis.types.end() && type_it->second.kind == TypeKind::RayQuery;
}

bool is_ray_payload_variable(std::uint32_t id, const Analysis& analysis) {
    const auto variable_it = analysis.variables.find(id);
    return variable_it != analysis.variables.end() &&
           (variable_it->second.storage_class == StorageClass::RayPayloadKHR ||
            variable_it->second.storage_class == StorageClass::IncomingRayPayloadKHR);
}

std::string pointer_expr(std::uint32_t id,
                         const Analysis& analysis,
                         const std::unordered_map<std::uint32_t, std::string>& pointers) {
    const auto pointer_it = pointers.find(id);
    if (pointer_it != pointers.end()) return pointer_it->second;
    if (is_ray_query_variable(id, analysis)) return "&" + id_name(id, analysis, "rq_");
    if (is_ray_payload_variable(id, analysis)) return "&" + id_name(id, analysis, "payload_");
    if (is_acceleration_structure_variable(id, analysis)) return id_name(id, analysis, "accel_");
    if (pointer_is_interface_variable(id, analysis)) return id_name(id, analysis, "ptr_") + "[0]";
    return "ptr_" + std::to_string(id);
}

std::string builtin_component_expr(std::uint32_t builtin, std::uint32_t component, Target target) {
    if (builtin == 28) { // GlobalInvocationId
        const char axis = component == 0 ? 'x' : component == 1 ? 'y' : 'z';
        if (target == Target::CUDA) {
            return "((uint32_t)(blockIdx." + std::string(1, axis) + " * blockDim." +
                   std::string(1, axis) + " + threadIdx." + std::string(1, axis) + "))";
        }
        return "global_invocation_id_" + std::string(1, axis);
    }
    return "builtin_" + std::to_string(builtin) + "_" + std::to_string(component);
}

void emit_lowered_body(std::ostringstream& out,
                       const Module& module,
                       const Analysis& analysis,
                       Target target) {
    std::unordered_map<std::uint32_t, std::string> expressions;
    std::unordered_map<std::uint32_t, std::string> pointers;
    std::unordered_map<std::uint32_t, std::uint32_t> loaded_builtins;
    bool in_function = false;

    for (const auto& [id, variable] : analysis.variables) {
        if (variable.storage_class == StorageClass::Private && is_ray_query_variable(id, analysis)) {
            out << "    vksplat_ray_query " << id_name(id, analysis, "rq_") << " = { 0u, 0u };\n";
        } else if (is_ray_payload_variable(id, analysis)) {
            out << "    " << c_type_for_id(variable.pointee_type_id, analysis) << " "
                << id_name(id, analysis, "payload_") << " = 0;\n";
        }
    }

    for (const Instruction& inst : module.instructions) {
        switch (inst.opcode) {
            case 54: // OpFunction
                in_function = true;
                break;
            case 56: // OpFunctionEnd
                in_function = false;
                break;
            case 43: { // OpConstant
                if (inst.operands.size() >= 2) {
                    const auto it = analysis.constants.find(inst.operands[1]);
                    if (it != analysis.constants.end()) {
                        expressions[inst.operands[1]] = constant_expr(it->second, analysis);
                    }
                }
                break;
            }
            case 62: { // OpStore
                if (!in_function || inst.operands.size() < 2) break;
                const std::uint32_t pointer_id = inst.operands[0];
                const std::uint32_t object_id = inst.operands[1];
                if (pointer_is_interface_variable(pointer_id, analysis) ||
                    pointers.find(pointer_id) != pointers.end()) {
                    out << "    " << pointer_expr(pointer_id, analysis, pointers) << " = "
                        << value_expr(object_id, analysis, expressions) << ";\n";
                } else {
                    out << "    /* unsupported OpStore target %" << pointer_id << " */\n";
                }
                break;
            }
            case 61: { // OpLoad
                if (!in_function || inst.operands.size() < 3) break;
                const auto variable_it = analysis.variables.find(inst.operands[2]);
                if (variable_it != analysis.variables.end() && variable_it->second.has_builtin) {
                    loaded_builtins[inst.operands[1]] = variable_it->second.builtin;
                } else if (is_ray_payload_variable(inst.operands[2], analysis)) {
                    expressions[inst.operands[1]] = id_name(inst.operands[2], analysis, "payload_");
                } else {
                    expressions[inst.operands[1]] = pointer_expr(inst.operands[2], analysis, pointers);
                }
                break;
            }
            case 80: { // OpCompositeConstruct
                if (!in_function || inst.operands.size() < 3) break;
                std::ostringstream expr;
                expr << "vksplat_make_float3(";
                for (std::size_t i = 2; i < inst.operands.size(); ++i) {
                    if (i != 2) expr << ", ";
                    expr << value_expr(inst.operands[i], analysis, expressions);
                }
                expr << ")";
                expressions[inst.operands[1]] = expr.str();
                break;
            }
            case 81: { // OpCompositeExtract
                if (!in_function || inst.operands.size() < 4) break;
                const std::uint32_t result_id = inst.operands[1];
                const std::uint32_t composite_id = inst.operands[2];
                const std::uint32_t component = inst.operands[3];
                const auto builtin_it = loaded_builtins.find(composite_id);
                if (builtin_it != loaded_builtins.end()) {
                    expressions[result_id] = builtin_component_expr(builtin_it->second, component, target);
                } else {
                    expressions[result_id] =
                        value_expr(composite_id, analysis, expressions) + "[" + std::to_string(component) + "]";
                }
                break;
            }
            case 65: { // OpAccessChain
                if (!in_function || inst.operands.size() < 4) break;
                const std::uint32_t result_id = inst.operands[1];
                const std::uint32_t base_id = inst.operands[2];
                if (!pointer_is_interface_variable(base_id, analysis)) {
                    pointers[result_id] = "ptr_" + std::to_string(result_id);
                    break;
                }

                std::size_t index_operand = 3;
                if (inst.operands.size() >= 5) {
                    const std::string first = value_expr(inst.operands[3], analysis, expressions);
                    if (first == "0" || first == "0u") index_operand = 4;
                }

                std::string index = "0";
                if (index_operand < inst.operands.size()) {
                    index = value_expr(inst.operands[index_operand], analysis, expressions);
                }
                pointers[result_id] = id_name(base_id, analysis, "ptr_") + "[" + index + "]";
                break;
            }
            case 128: { // OpIAdd
                if (!in_function || inst.operands.size() < 4) break;
                expressions[inst.operands[1]] = "(" +
                    value_expr(inst.operands[2], analysis, expressions) + " + " +
                    value_expr(inst.operands[3], analysis, expressions) + ")";
                break;
            }
            case 4473: { // OpRayQueryInitializeKHR
                if (!in_function || inst.operands.size() < 8) break;
                out << "    vksplat_ray_query_initialize("
                    << pointer_expr(inst.operands[0], analysis, pointers) << ", "
                    << value_expr(inst.operands[1], analysis, expressions) << ", "
                    << value_expr(inst.operands[2], analysis, expressions) << ", "
                    << value_expr(inst.operands[3], analysis, expressions) << ", "
                    << value_expr(inst.operands[4], analysis, expressions) << ", "
                    << value_expr(inst.operands[5], analysis, expressions) << ", "
                    << value_expr(inst.operands[6], analysis, expressions) << ", "
                    << value_expr(inst.operands[7], analysis, expressions) << ");\n";
                break;
            }
            case 4445: { // OpTraceRayKHR
                if (!in_function || inst.operands.size() < 11) break;
                out << "    vksplat_trace_ray("
                    << value_expr(inst.operands[0], analysis, expressions) << ", "
                    << value_expr(inst.operands[1], analysis, expressions) << ", "
                    << value_expr(inst.operands[2], analysis, expressions) << ", "
                    << value_expr(inst.operands[3], analysis, expressions) << ", "
                    << value_expr(inst.operands[4], analysis, expressions) << ", "
                    << value_expr(inst.operands[5], analysis, expressions) << ", "
                    << value_expr(inst.operands[6], analysis, expressions) << ", "
                    << value_expr(inst.operands[7], analysis, expressions) << ", "
                    << value_expr(inst.operands[8], analysis, expressions) << ", "
                    << value_expr(inst.operands[9], analysis, expressions) << ", "
                    << pointer_expr(inst.operands[10], analysis, pointers) << ");\n";
                break;
            }
            case 4477: { // OpRayQueryProceedKHR
                if (!in_function || inst.operands.size() < 3) break;
                expressions[inst.operands[1]] =
                    "vksplat_ray_query_proceed(" + pointer_expr(inst.operands[2], analysis, pointers) + ")";
                break;
            }
            case 4479: { // OpRayQueryGetIntersectionTypeKHR
                if (!in_function || inst.operands.size() < 4) break;
                expressions[inst.operands[1]] =
                    "vksplat_ray_query_intersection_type(" +
                    pointer_expr(inst.operands[2], analysis, pointers) + ", " +
                    value_expr(inst.operands[3], analysis, expressions) + ")";
                break;
            }
            default:
                break;
        }
    }

    if (expressions.empty()) {
        out << "    /* no lowered operations in supported subset. */\n";
    }
}

} // namespace

KernelInterface describe_kernel_interface(const Module& module,
                                          const TranslationOptions& options) {
    const EntryPoint& ep = first_entry_point(module);
    const Analysis analysis = analyze_module(module);

    KernelInterface interface;
    interface.entry_point = sanitize_identifier(ep.name, options.module_name);
    interface.execution_model = ep.execution_model;
    interface.uses_global_invocation_id = has_global_invocation_id(analysis);

    const std::vector<Variable> variables = interface_variables(analysis);
    interface.parameters.reserve(variables.size());
    for (const Variable& variable : variables) {
        KernelParameter parameter;
        parameter.variable_id = variable.id;
        parameter.name = id_name(variable.id, analysis, "ptr_");
        parameter.c_type = parameter_type(variable, analysis);
        parameter.storage_class = variable.storage_class;
        parameter.has_descriptor_set = variable.has_descriptor_set;
        parameter.descriptor_set = variable.descriptor_set;
        parameter.has_binding = variable.has_binding;
        parameter.binding = variable.binding;
        interface.parameters.push_back(std::move(parameter));
    }

    return interface;
}

std::string format_kernel_interface_json(const KernelInterface& interface) {
    std::ostringstream out;
    out << "{\n";
    out << "  \"entry_point\": \"" << json_escape(interface.entry_point) << "\",\n";
    out << "  \"execution_model\": \"" << execution_model_name(interface.execution_model) << "\",\n";
    out << "  \"uses_global_invocation_id\": "
        << (interface.uses_global_invocation_id ? "true" : "false") << ",\n";
    out << "  \"parameters\": [\n";
    for (std::size_t i = 0; i < interface.parameters.size(); ++i) {
        const KernelParameter& parameter = interface.parameters[i];
        out << "    {\n";
        out << "      \"variable_id\": " << parameter.variable_id << ",\n";
        out << "      \"name\": \"" << json_escape(parameter.name) << "\",\n";
        out << "      \"c_type\": \"" << json_escape(parameter.c_type) << "\",\n";
        out << "      \"storage_class\": \"" << storage_class_name(parameter.storage_class) << "\",\n";
        out << "      \"descriptor_set\": ";
        if (parameter.has_descriptor_set) {
            out << parameter.descriptor_set;
        } else {
            out << "null";
        }
        out << ",\n";
        out << "      \"binding\": ";
        if (parameter.has_binding) {
            out << parameter.binding;
        } else {
            out << "null";
        }
        out << "\n";
        out << "    }" << (i + 1 == interface.parameters.size() ? "\n" : ",\n");
    }
    out << "  ]\n";
    out << "}\n";
    return out.str();
}

std::string translate_to_c(const Module& module, const TranslationOptions& options) {
    const EntryPoint& ep = first_entry_point(module);
    const Analysis analysis = analyze_module(module);
    const std::string name = sanitize_identifier(ep.name, options.module_name);

    std::ostringstream out;
    emit_header(out, module, "C");
    out << "#include <stdint.h>\n\n";
    out << "typedef struct { float x, y, z; } vksplat_float3;\n";
    out << "typedef struct { uint32_t active; uint32_t committed_type; } vksplat_ray_query;\n";
    out << "static inline vksplat_float3 vksplat_make_float3(float x, float y, float z) { return (vksplat_float3){ x, y, z }; }\n";
    out << "void vksplat_ray_query_initialize(vksplat_ray_query* rq, const void* accel, uint32_t flags, uint32_t mask, vksplat_float3 origin, float tmin, vksplat_float3 direction, float tmax);\n";
    out << "uint8_t vksplat_ray_query_proceed(vksplat_ray_query* rq);\n";
    out << "uint32_t vksplat_ray_query_intersection_type(vksplat_ray_query* rq, uint32_t intersection);\n\n";
    out << "void vksplat_trace_ray(const void* accel, uint32_t flags, uint32_t mask, uint32_t sbt_offset, uint32_t sbt_stride, uint32_t miss_index, vksplat_float3 origin, float tmin, vksplat_float3 direction, float tmax, void* payload);\n\n";
    out << "void " << name << "(" << parameter_list(analysis, Target::C) << ") {\n";
    out << "    /* execution_model: " << execution_model_name(ep.execution_model) << " */\n";
    emit_lowered_body(out, module, analysis, Target::C);
    out << "}\n";
    return out.str();
}

std::string translate_to_cuda(const Module& module, const TranslationOptions& options) {
    const EntryPoint& ep = first_entry_point(module);
    const Analysis analysis = analyze_module(module);
    const std::string name = sanitize_identifier(ep.name, options.module_name);

    std::ostringstream out;
    emit_header(out, module, "CUDA");
    out << "#include <stdint.h>\n\n";
    out << "struct vksplat_float3 { float x, y, z; };\n";
    out << "struct vksplat_ray_query { uint32_t active; uint32_t committed_type; };\n";
    out << "__device__ inline vksplat_float3 vksplat_make_float3(float x, float y, float z) { return { x, y, z }; }\n";
    out << "__device__ void vksplat_ray_query_initialize(vksplat_ray_query* rq, const void* accel, uint32_t flags, uint32_t mask, vksplat_float3 origin, float tmin, vksplat_float3 direction, float tmax);\n";
    out << "__device__ uint8_t vksplat_ray_query_proceed(vksplat_ray_query* rq);\n";
    out << "__device__ uint32_t vksplat_ray_query_intersection_type(vksplat_ray_query* rq, uint32_t intersection);\n\n";
    out << "__device__ void vksplat_trace_ray(const void* accel, uint32_t flags, uint32_t mask, uint32_t sbt_offset, uint32_t sbt_stride, uint32_t miss_index, vksplat_float3 origin, float tmin, vksplat_float3 direction, float tmax, void* payload);\n\n";
    out << "extern \"C\" __global__ void " << name << "_kernel(" << parameter_list(analysis, Target::CUDA) << ") {\n";
    out << "    /* execution_model: " << execution_model_name(ep.execution_model) << " */\n";
    emit_lowered_body(out, module, analysis, Target::CUDA);
    out << "}\n";
    return out.str();
}

} // namespace vksplat::spirv
